/* Additional record code for Decay generated by the OpenModelica Compiler OpenModelica 1.26.9. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Decay_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

