# Generated by crew.
FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip install -e . || pip install -r requirements.txt || true
RUN useradd -m app && chown -R app /app
USER app
CMD ["python","-m","app"]
