"""Real KiCad validation + export via the ``kicad-cli`` binary.

cad/kicad.py emits KiCad files and self-checks them with a regex verifier; this test
closes the loop with the ground truth — the actual ``kicad-cli`` consuming the files:

  * a PCB generated by the electronics path (``validate_pcb_with_kicad_cli``) is
    LOADED by KiCad and exported to SVG + Gerbers + STEP — KiCad genuinely parsed the
    board (real validation) and produced real manufacturing artifacts;
  * a netlist is exported from a REAL KiCad demo schematic — the schematic-validation
    path proven on input KiCad accepts;
  * NEGATIVE: a malformed ``.kicad_pcb`` is REJECTED by KiCad (ok=False with KiCad's
    message), never a fabricated pass; the missing-binary path raises ToolError.

Named ``*_integration.py`` (spawns kicad-cli) and SKIPS when kicad-cli is absent —
on the GENESIS box KiCad 7 is installed, so this PASSES.

Run:  PYTHONPATH=src .venv/bin/python -m pytest tests/test_kicad_cli_integration.py -q
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from gen.cad import kicad_cli as kc  # noqa: E402
from gen.core.errors import ToolError  # noqa: E402

if not kc.kicad_cli_available():
    pytest.skip("kicad-cli not on PATH", allow_module_level=True)


def _placements_and_components():
    from gen.electronics import Component, PlacementHint

    comps = [
        Component(
            id="R1", name="10k", kind="sensor", v_nom=3.3, i_max=0.01,
            p_max_dissip=0.1, footprint_mm=(2.0, 1.25, 0.5), package="R_0805_2012Metric",
        ),
        Component(
            id="C1", name="100nF", kind="sensor", v_nom=3.3, i_max=0.01,
            p_max_dissip=0.1, footprint_mm=(2.0, 1.25, 0.5), package="C_0805_2012Metric",
        ),
    ]
    placements = [
        PlacementHint(ref_des="R1", pos_mm=(10.0, 10.0, 0.0), rot_deg=(0.0, 0.0, 0.0),
                      footprint="R_0805_2012Metric"),
        PlacementHint(ref_des="C1", pos_mm=(20.0, 10.0, 0.0), rot_deg=(0.0, 0.0, 90.0),
                      footprint="C_0805_2012Metric"),
    ]
    return placements, comps


def test_version_is_kicad():
    v = kc.kicad_version()
    assert v and v[0].isdigit()  # e.g. "7.0.11"


def test_generated_pcb_is_loaded_and_exported_by_kicad(tmp_path):
    """The electronics PCB path -> KiCad loads it -> SVG + Gerbers + STEP. KiCad
    accepting + exporting is the real validation our regex verifier cannot give."""
    from gen.electronics import validate_pcb_with_kicad_cli

    placements, comps = _placements_and_components()
    res = validate_pcb_with_kicad_cli(
        placements, comps, str(tmp_path), formats=("svg", "gerbers", "step")
    )
    assert res["available"] is True
    assert Path(res["pcb_path"]).is_file()
    assert res["ok"] is True, res["results"]

    svg = res["results"]["svg"]
    assert svg.ok and svg.outputs and Path(svg.outputs[0]).stat().st_size > 0
    gerb = res["results"]["gerbers"]
    assert gerb.ok and any(p.endswith(".gbrjob") for p in gerb.outputs)
    step = res["results"]["step"]
    assert step.ok and step.outputs and Path(step.outputs[0]).stat().st_size > 0


def test_netlist_export_from_real_demo_schematic(tmp_path):
    """KiCad emits a netlist from a real KiCad-authored schematic — the schematic
    validation path proven on input KiCad accepts."""
    candidates = list(Path("/usr/share/kicad/demos").rglob("*.kicad_sch"))
    if not candidates:
        pytest.skip("no KiCad demo schematics installed to validate against")
    demo = candidates[0]
    out = tmp_path / "demo.net"
    res = kc.export_netlist(demo, out, fmt="kicadsexpr")
    assert res.ok, res.detail
    assert out.is_file() and out.stat().st_size > 0
    assert out.read_text(encoding="utf-8").lstrip().startswith("(export")


# --- Negative tests: never a fabricated pass --------------------------------

def test_malformed_pcb_is_rejected_by_kicad(tmp_path):
    """A syntactically-broken .kicad_pcb makes KiCad fail; export_pcb reports ok=False
    (with KiCad's message), not a fabricated success."""
    bad = tmp_path / "broken.kicad_pcb"
    bad.write_text("(this is not a valid kicad board at all", encoding="utf-8")
    res = kc.export_pcb(bad, tmp_path, fmt="svg")
    assert res.ok is False
    assert not res.outputs  # KiCad wrote nothing


def test_empty_output_not_reported_as_success(tmp_path):
    """KiCad's exit-0-but-no-output failure mode (a nonexistent-but-named board that
    can't render) must yield ok=False — the _run_cli guard requires real output."""
    # an empty (zero-net, no-layer-content) garbage file
    bad = tmp_path / "empty.kicad_pcb"
    bad.write_text("(kicad_pcb)", encoding="utf-8")
    res = kc.export_pcb(bad, tmp_path, fmt="gerbers")
    assert res.ok is False


def test_missing_binary_raises_tool_error(monkeypatch, tmp_path):
    """Pointing the adapter at a nonexistent binary raises ToolError, loud."""
    monkeypatch.setenv("GENESIS_KICAD_CLI", "kicad-cli-does-not-exist-xyz")
    assert kc.kicad_cli_available() is False
    placements, comps = _placements_and_components()
    bad = tmp_path / "x.kicad_pcb"
    bad.write_text("(kicad_pcb)", encoding="utf-8")
    with pytest.raises(ToolError):
        kc.export_pcb(bad, tmp_path, fmt="svg")
    with pytest.raises(ToolError):
        kc.kicad_version()
