#!/usr/bin/env python3
"""gen_status.py — regenerate the AUTO-GENERATED block inside docs/STATUS.md.

STATUS.md is the single source of truth. Its top half is CURATED (judgement: the
integrity watchlist, the CLI-mode truth table, the HORIZON status, the island triage).
Its bottom half is MACHINE-GENERATED by this script so the *numbers* can never drift:
  - live test count (pytest --collect-only)
  - module reachability totals + the full island list (via find_islands.py)
  - technical-debt marker counts

Only the text between the  <!-- AUTO:BEGIN -->  and  <!-- AUTO:END -->  markers is
rewritten; everything else is left exactly as a human wrote it.

Usage:  python scripts/gen_status.py [--date YYYY-MM-DD]
"""
from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import find_islands  # noqa: E402

STATUS = ROOT / "docs" / "STATUS.md"
VENV_PY = ROOT / ".venv" / "bin" / "python"
PY = str(VENV_PY) if VENV_PY.exists() else sys.executable

DEBT_MARKERS = ["NotImplementedError", "TODO", "FIXME", "first-stone", "first stone",
                "skeleton", "stub", "placeholder", "demo", "hardcoded", "HACK"]


def test_count() -> str:
    try:
        out = subprocess.run([PY, "-m", "pytest", "--collect-only", "-q"],
                             cwd=ROOT, capture_output=True, text=True, timeout=300)
        m = re.search(r"(\d+)\s+tests? collected", out.stdout + out.stderr)
        return f"{m.group(1)} collected" if m else "collection failed (see pytest output)"
    except subprocess.TimeoutExpired:
        return "timeout (>300s collecting)"
    except Exception as e:  # noqa: BLE001
        return f"unavailable ({e.__class__.__name__})"


def debt_counts() -> dict[str, int]:
    counts = {k: 0 for k in DEBT_MARKERS}
    for p in (ROOT / "src" / "gen").rglob("*.py"):
        if "__pycache__" in p.parts:
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        low = text.lower()
        for k in DEBT_MARKERS:
            counts[k] += low.count(k.lower())
    return counts


def _island_lines(islands: list[dict], tag: str) -> str:
    names = sorted(r["module"] for r in islands if r["tag"] == tag)
    if not names:
        return "_(none)_"
    return ", ".join(f"`{n}`" for n in names)


def build_block(date: str) -> str:
    data = find_islands.analyze()
    t = data["totals"]
    islands = data["islands"]
    debt = debt_counts()
    L = []
    L.append(f"_Auto-generated by `scripts/gen_status.py` on **{date}**. Do not edit by hand — re-run the script._")
    L.append("")
    L.append("### Reachability (via `scripts/find_islands.py`)")
    L.append("")
    L.append(f"| modules | WIRED | SCRIPT (runnable, not wired) | ISLAND (no caller) | INFRA |")
    L.append(f"|--:|--:|--:|--:|--:|")
    L.append(f"| {t['modules']} | {t.get('WIRED',0)} | {t.get('SCRIPT',0)} | {t.get('ISLAND',0)} | {t.get('INFRA',0)} |")
    L.append("")
    L.append(f"**Live test suite:** {test_count()}")
    L.append("")
    L.append(f"**Islands by category** ({len(islands)} total — real code, no production caller):")
    L.append("")
    L.append(f"- **facade-only** (imported only by a package `__init__` re-export — false liveness): {_island_lines(islands,'facade-only')}")
    L.append("")
    L.append(f"- **test-only** (imported only by tests): {_island_lines(islands,'test-only')}")
    L.append("")
    L.append(f"- **transitive** (imported only by other islands): {_island_lines(islands,'transitive')}")
    L.append("")
    L.append(f"- **orphan** (imported by nobody at all): {_island_lines(islands,'orphan')}")
    L.append("")
    L.append(f"**Standalone scripts** ({t.get('SCRIPT',0)} — runnable via `__main__`, not pipeline-wired): "
             + ", ".join(f"`{m}`" for m in data["scripts"]))
    L.append("")
    L.append("### Technical-debt markers in `src/gen`")
    L.append("")
    L.append("| marker | count |")
    L.append("|---|--:|")
    for k in DEBT_MARKERS:
        L.append(f"| `{k}` | {debt[k]} |")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=datetime.date.today().isoformat())
    args = ap.parse_args(argv)
    if not STATUS.exists():
        print(f"ERROR: {STATUS} does not exist. Create it (with AUTO markers) first.", file=sys.stderr)
        return 1
    text = STATUS.read_text(encoding="utf-8")
    block = build_block(args.date)
    new = re.sub(r"<!-- AUTO:BEGIN -->.*<!-- AUTO:END -->",
                 f"<!-- AUTO:BEGIN -->\n{block}\n<!-- AUTO:END -->",
                 text, flags=re.DOTALL)
    if new == text and "<!-- AUTO:BEGIN -->" not in text:
        print("ERROR: no <!-- AUTO:BEGIN -->/<!-- AUTO:END --> markers found in STATUS.md", file=sys.stderr)
        return 1
    STATUS.write_text(new, encoding="utf-8")
    print(f"Updated {STATUS.relative_to(ROOT)} (date {args.date}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
